Rails Capstone Project: FINAL REVIEW
AbdimulhinYussuf3675/Budget-app pull request #9
Opened 2023-06-02 01:20 UTC by AbdimulhinYussuf3675

### BUDGET APP
**During this capstone project, I successfully achieved the following milestones:**

- I used `Ruby and Ruby on Rails (RoR)` design this RESTful application.
- The application includes several models based on an [Entity-Relationship Diagram (ERD) in PostgresSQL](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/images/erd_diagram.png). The models include
- User, Group, Expense, and a bridge tables.
- Authentication is implemented using Devise, while authorization is handled by cancancan.
- An unauthorized user is presented with a splash screen upon accessing the application.
- The category page serves as the home page for the application.
- A transaction page has been created.
- Unit and integration tests have been written using RSpec.
- Authenticated users have the ability to create groups and expenses.
- I have recorded a video presentation showcasing the project's details. please check below
- The web service has been deployed on the Render site, as shown below
- The design of the application adhered to a mobile-first approach
### Project presentation video record_button . To watch the video please click the link below [`link`](url)

2023-06-02 21:31 UTC, BregornOriginal requested changes
Hi @AbdimulhinYussuf3675  

Good job so far!

There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![giphy (5)](https://github.com/AbdimulhinYussuf3675/Budget-app/assets/93630700/cc489ebd-a332-4ecc-8e7d-fea47a65256e)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-02 21:31 UTC, BregornOriginal commented on README.md
> +### Take a look at project's [Live Demo](https://budgetapp-7px9.onrender.com/)
- [ ] Kindly fix the link to your live version, there's a black screen on that link

2023-06-02 21:31 UTC, BregornOriginal commented on README.md
> +I would like to thank...
- [ ] As was requested in the requirements, kindly gives in this section [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/).

2023-06-03 03:07 UTC, addod19 approved these changes
### Hi @AbdimulhinYussuf3675, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Nice job fixing the deployed link :+1: 

**NB**: YOU DID NOT FOLLOW THE CORRECT GIT-FLOW WORKFLOW BUT INSTEAD OF THE PROJECT BEING INVALIDATED, IT HAS BEEN REVIEWED. PLEASE TRY AND FOLLOW PROJECT GUIDELINES. GIT-FLOW MEANS CREATING A PR FROM A DESCRIPTIVE FEATURE BRANCH, FOR EXAMPLE `BUDGET` OR ANY DESCRIPTIVE NAME YOU MAY CHOOSE INTO THE `DEV` BRANCH. THAT IS GIT-FLOW


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 03:12 UTC, AbdimulhinYussuf3675 commented
Thanks @addod19,  Sure I will fix it

2023-06-03 03:13 UTC, merged